### ISSUE TITLE
Sprung-Bug in Testszene 4

### ISSUE THREAD

**Issue by stefan-s29** [LMUOGWSS2015/Gruppe4#1]
Wenn man in der Testszene stefan_tree4 am Checkpoint auf der mittleren Plattform startet, kann man nicht springen, solange bis man sich auf eine andere Plattform hat runterfallen lassen. Wenn man von unten startet, kann man an der Checkpoint-Plattform ganz normal springen.

**Comment by Paaadi** [comment]
Ist Gefixt!!!
Problem war, dass du den Checkpoint IN die Platform rein gemacht hast.
Also aufpassen, der Checkpoint darf natürlich nicht in Gegenständen etc. drin sein, da sonst der Player eben darin gespawnt wird, was zu Fehlern führt.
