### ISSUE TITLE
Spielergeräusche

### ISSUE THREAD

**Issue by Paaadi** [LMUOGWSS2015/Gruppe4#14]
Sound beim Laufen, Springen, ...

**Comment by Hamster3001** [comment]
Sounds sind geadded. Entsprechende Funktionen finden sich im PlayerSkript. Die Schrittlautstärke sowie der Abstand werden variiert. Die Sounds können im PlayerPrefab im AudioClips Array noch durch andere ersetzt werden, für den walking sound müssen aber parameter angepasst werden. [0]= walk, [1]=jump, [2]=doublejump.
