### ISSUE TITLE
Schwingen der Pendel

### ISSUE THREAD

**Issue by stefan-s29** [LMUOGWSS2015/Gruppe4#3]
Für das schwingende Pendel gibt es jetzt ein Modell von Linh mit Stachelklinge unten dran. Das Modell findet ihr unter Environment/Standard Models/. Damit es auch schwingt, habe ich mein Skript eingebaut und damit mein altes "Pendulum"-Prefab überschrieben. Das liegt unter Levels/Prefabs/. Ich musste leider das alte Prefab verwenden, damit die schon bestehenden Pendel automatisch ersetzt werden. Zum Hinzufügen von Pendeln jetzt bitte mein Prefab verwenden.

Leider schwingt das Pendel oft nicht so, wie es soll. Es soll eigentlich entlang der Längsachse jeweils bis zu einem 45-Grad-Winkel schwingen. Entsprechend ist als Schwing-Achse im RotationCenter-Objekt die X-Achse eingestellt. Nun sollte man das Pendulum-Prefab einfach um 90 Grad drehen können und es sollte dann entsprechend in eine andere Richtung schwingen. Das funktioniert jedoch zum Beispiel in test_parcour beim letzten Pendel vor dem Ziel nicht. Wenn man ein neues Pendel einfügt und es an die Position verschiebt und um 90 Grad dreht, ist es zwar gedreht, schwingt aber trotzdem in die ursprüngliche Richtung. Wenn es dem "Level"-GameObjekt untergeordnet ist, bekommt es dafür sehr abenteuerliche Rotationswerte...

Am Schwing-Skript sollte das eigentlich nicht liegen, da das ja wirklich einfach entlang bestimmter Achsen rotiert und da kann man nicht viel falsch machen... Woran dann? Eventuell an der Rotation der Unterelemente?

**Comment by tomwim** [comment]
Problem war im Code, ist aber gelöst.
