### ISSUE TITLE
Menüsteuerung mit Controller

### ISSUE THREAD

**Issue by Paaadi** [LMUOGWSS2015/Gruppe4#4]

**Comment by tomwim** [comment]
Meinst du es ist auch mit Gaze möglich? Rechts schauen, rotierts nach rechts, links nach links

**Comment by Paaadi** [comment]
ja geht bestimmt. evtl. könnt man da ja zwei so kristalle irgendwo hin machen wo man dann drauf schauen muss

**Comment by Paaadi** [comment]
das mit der Gaze-Steuerung im Menü lass mer glaub lieber.
Das ist sonst zu viel aufwand für zu wenig ertrag ;)
