### ISSUE TITLE
Auswahl von Levels über das Menü

### ISSUE THREAD

**Issue by Paaadi** [LMUOGWSS2015/Gruppe4#7]
Durch Auswahl eines Levels im Menü sollte das entsprechende Level geladen werden.

**Comment by tomwim** [comment]
Hab ich aufm Schirm und werd ich noch machen, sobald wir die Levels auch wirklich haben.

**Comment by Paaadi** [comment]
hab schon rausgefunden wie das geht ;)

**Comment by Paaadi** [comment]
Funktioniert!!
Evtl. noch asynchron laden.
